import MainHeader from "@/components/main-header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ContentLayout({ children }) {
  return (
    <div id="page">
      <MainHeader />
      {children}
    </div>
  );
}
